services:
  cs-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_TYPE: ${SERVER_TYPE:-classic}
    image: cs16-server:${SERVER_TYPE:-classic}
    container_name: cs-server-${SERVER_TYPE:-classic}
    environment:
      - MAXPLAYERS=${CS_SERVER_MAXPLAYERS:-16}
      - MAP=${CS_SERVER_MAP:-de_dust2}
      - PORT=${CS_SERVER_PORT:-27015}
      - RCON_PASSWORD=${RCON_PASSWORD:-changeme}
      - SERVERCFG=/home/steam/csserver/cstrike/server.cfg
    volumes:
      # Mount logs for persistence (read-write only)
      - ./logs:/home/steam/csserver/cstrike/logs
    ports:
      - "${CS_SERVER_PORT:-27015}:${CS_SERVER_PORT:-27015}/udp"
    networks:
      - cs-network
    restart: unless-stopped

networks:
  cs-network:
    driver: bridge