version: '3.8'

services:
  cs16-hybrid:
    build: .
    ports:
      - "8080:8080"   # Go WebRTC Server (Web Client)
      - "3000:3000"   # Python API Server (Metrics/Dashboard)
    environment:
      - RELAY_DEFAULT_BACKEND_HOST=host.docker.internal
      - RELAY_DEFAULT_BACKEND_PORT=27015
      - DM_PORT=27016
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped