version: "3.8"
services:
  cs16_pub:
    image: hldsdocker/rehlds-cstrike:latest
    container_name: cs16_pub
    environment:
      - MAXPLAYERS=16
      - MAP=de_dust2
      - PORT=27015
      - SERVERCFG=/opt/cstrike/server.cfg
    volumes:
      - ./server.cfg:/opt/cstrike/server.cfg:ro
      - ./motd.txt:/opt/cstrike/motd.txt:ro
      - ./mapcycle.txt:/opt/cstrike/mapcycle.txt:ro
      - ./addons:/opt/cstrike/addons
      - ./maps:/opt/cstrike/maps
      - ./overviews:/opt/cstrike/overviews
    ports:
      - "27015:27015/udp"
    command: ["./hlds_run", "-game", "cstrike", "+maxplayers", "16", "+map", "de_dust2", "-port", "27015", "-pingboost", "2", "+exec", "server.cfg"]
    restart: unless-stopped

# Temporarily disabled - using only classic server for now
  # cs16_dm:
  #   image: hldsdocker/rehlds-cstrike:latest
  #   container_name: cs16_dm
  #   environment:
  #     - MAXPLAYERS=16
  #     - MAP=de_inferno
  #     - PORT=27016
  #     - SERVERCFG=/opt/cstrike/server.cfg
  #   volumes:
  #     - ./server.cfg:/opt/cstrike/server.cfg:ro
  #     - ./motd.txt:/opt/cstrike/motd.txt:ro
  #     - ./mapcycle.txt:/opt/cstrike/mapcycle.txt:ro
  #     - ./addons:/opt/cstrike/addons
  #     - ./maps:/opt/cstrike/maps
  #     - ./overviews:/opt/cstrike/overviews
  #   network_mode: "host"
  #   restart: unless-stopped
